spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhengchengcrp?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver