# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000
  port: 8090

spring:
  profiles:
    active: dev
  # 环境 dev|test|pro
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #    jmx.enabled: false


  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:com/wl/dao/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wl.domain.**
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.wanglei.springboot.api.admin.config.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false